### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by Viswas-Programs** [North-West-Wind/opensurviv-client#11]
Can we publicise this project, like the people of surviv reloaded. Creating discord servers, subreddits, and hosting this on a server and things like that?

I asked this, because of the popularity gain of surviv reloaded, by just creating a sub reddit and discord server

**Comment by NihalNavath** [comment]
This project is still not completed, and isn't even in a playable state right now, how do you expect to host a server for it. Once it is playable I can host a version on my server.

**Comment by Viswas-Programs** [comment]
Ok like future plans. 
And, btw did you fix that problem about the GDI glitch with this game?

**Comment by North-West-Wind** [comment]
If you want to publicise this, go for it. The reason I didn't/won't do it myself is because:
1. I'm terrible at managing communities.
2. I don't like making promises. Even though I'm passionate about this project, I can't be sure if I can finish it.

Also, the differences between opensurviv and survivreloaded is that we are rewriting the entire thing from scratch, because one of my goals is to support modding.
